local text_original = LocalizationManager.text
function LocalizationManager:text(string_id, ...)

return string_id == "PBC_NAME" and "PBC"
or string_id == "PBC_DESC" and "Decreases your recoil, increases your fire rate and your overall durability. Speed is greatly reduced though."
or string_id == "PBC_NAME_PK1" and "Armor Boost"
or string_id == "PBC_DESC_PK1" and "Armor increased to ##400%##"
or string_id == "PBC_NAME_PK2" and "Adrenaline to go"
or string_id == "PBC_DESC_PK2" and "Health increased to ##300%## and makes your health ##regenerate##"
or string_id == "PBC_NAME_PK3" and "Ammo Pouch"
or string_id == "PBC_DESC_PK3" and "Total Ammo increased to ##350%##, increases your ammo pickup to ##200%## and increases your ammo pickup range to ##300%##"
or string_id == "PBC_NAME_PK4" and "Shotgun Expert"
or string_id == "PBC_DESC_PK4" and "##Decreases shotgun recoil##, increases the fire rate to ##200%## and ##doubles## the reloads speed"
or string_id == "PBC_NAME_PK5" and "War Veteran"
or string_id == "PBC_DESC_PK5" and "##Decreases LMG recoil##, increases the fire rate to ##200%## and ##doubles## the reloads speed"
or string_id == "PBC_NAME_PK6" and "Personal defense weapon"
or string_id == "PBC_DESC_PK6" and "##Decreases SMG recoil##, increases the fire rate to ##200%## and ##doubles## the reloads speed"
or string_id == "PBC_NAME_PK7" and "Hitman"
or string_id == "PBC_DESC_PK7" and "##Decreases pistol recoil##, increases the fire rate to ##200%## and ##doubles## the reloads speed"
or string_id == "PBC_NAME_PK8" and "Professional Rifler"
or string_id == "PBC_DESC_PK8" and "##Decreases assault rifle recoil##, increases the fire rate to ##200%## and ##doubles## the reloads speed"
or string_id == "PBC_NAME_PK9" and "Heavy armor penalty"
or string_id == "PBC_DESC_PK9" and "##Decreases movement speed##"

or string_id == "DD_NAME" and "derDude"
or string_id == "DD_DESC" and "One hit your enemies using your melee weapon, get more jokers, be swift and carry bags around quickly. Just like Eric does. | To be able to have more jokers at the same time, make sure to not use Confident Aced! A bug currently prevents the joker effect from this perk deck to work with Confident Aced."
or string_id == "DD_NAME_PK1" and "Swiftness"
or string_id == "DD_DESC_PK1" and "Movement speed increased to ##150%##"
or string_id == "DD_NAME_PK2" and "Futuristic armor"
or string_id == "DD_DESC_PK2" and "Armor increased to ##1300%##"
or string_id == "DD_NAME_PK3" and "Energy pull"
or string_id == "DD_DESC_PK3" and "Max HP set to ##0##"
or string_id == "DD_NAME_PK4" and "Efficiency"
or string_id == "DD_DESC_PK4" and "Ammo pickup increased to ##200%##"
or string_id == "DD_NAME_PK5" and "Mechanic arm"
or string_id == "DD_DESC_PK5" and "All melee hits ##one hit##"
or string_id == "DD_NAME_PK6" and "Ninja-like"
or string_id == "DD_DESC_PK6" and "Dodge increased by ##10%##"
or string_id == "DD_NAME_PK7" and "Vegan lifestyle"
or string_id == "DD_DESC_PK7" and "Stamina increased to ##200%##"
or string_id == "DD_NAME_PK8" and "Influencer"
or string_id == "DD_DESC_PK8" and "Max Joker amount increased to ##4## | To be able to have more jokers at the same time, make sure to not use Confident Aced! A bug currently prevents the joker effect from this perk deck to work with Confident Aced."
or string_id == "DD_NAME_PK9" and "Heavy training"
or string_id == "DD_DESC_PK9" and "Bag carrying speed increased to ##200%##"

or text_original(self, string_id, ...)
end